### ISSUE TITLE
Atomation error since Home Assistant Core 2023.12.4 update

### ISSUE THREAD

**Issue by domotiquemaison07** [max13fr/Airzonecloud-HomeAssistant#39]
Hello,
I got a 429 error since I updated to Core 2023.12.4.
Temperatures are well updated but script stop due to 429 error.

Logger: homeassistant.components.automation.temperature_20
Source: helpers/script.py:468
Integration: Automatisation (documentation, issues)
First occurred: 18:29:37 (3 occurrences)
Last logged: 19:15:30

Température - 20: Error executing script. Unexpected error for call_service at pos 1: 429 Client Error: Too Many Requests for url: https://m.airzonecloud.com/api/v1/devices/******************/status/?installation_id=*****************&format=json
Température - 20: Error executing script. Unexpected error for call_service at pos 1: 429 Client Error: Too Many Requests for url: https://m.airzonecloud.com/api/v1/devices/*******************/status/?installation_id=*******************&format=json
Température - 20: Error executing script. Unexpected error for call_service at pos 1: 429 Client Error: Too Many Requests for url: https://m.airzonecloud.com/api/v1/devices/*******************/status/?installation_id=****************&format=json
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 468, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 704, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 666, in _async_run_long_action
    return long_task.result()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2067, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2104, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 272, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 903, in entity_service_call
    raise result from None
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1233, in async_request_call
    return await coro
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 948, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 632, in async_service_temperature_set
    await entity.async_set_temperature(**kwargs)
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 482, in async_set_temperature
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/airzonecloud/climate.py", line 166, in set_temperature
    self._device.set_temperature(round(float(temperature), 1))
  File "/usr/local/lib/python3.11/site-packages/AirzoneCloud/Device.py", line 254, in set_temperature
    self.refresh()
  File "/usr/local/lib/python3.11/site-packages/AirzoneCloud/Device.py", line 316, in refresh
    self._state = self._api._api_get_device_state(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/AirzoneCloud/AirzoneCloud.py", line 162, in _api_get_device_state
    return self._api_get(
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/AirzoneCloud/AirzoneCloud.py", line 210, in _api_get
    return self._api_request(method="GET", api_endpoint=api_endpoint, params=params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/AirzoneCloud/AirzoneCloud.py", line 293, in _api_request
    raise err
  File "/usr/local/lib/python3.11/site-packages/AirzoneCloud/AirzoneCloud.py", line 290, in _api_request
    call.raise_for_status()
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://m.airzonecloud.com/api/v1/devices/*****************/status/?installation_id=*********************&format=json

**Comment by domotiquemaison07** [comment]
Hello,
Everything seems fine since I updated my airzone server to 4.03

**Comment by domotiquemaison07** [comment]
I close the topic

**Comment by domotiquemaison07** [comment]
I reopen it because it is still not working

**Comment by riddle-stc** [comment]
I seem to get the same error in my log.
Temperature is not updated in Airzone.

**Comment by domotiquemaison07** [comment]
Found this Error in my log.

Logger: AirzoneCloud.AirzoneCloud
Source: custom_components/airzonecloud/climate.py:281
Integration: airzonecloud (documentation, issues)
First occurred: 28 décembre 2023 à 17:47:23 (25454 occurrences)
Last logged: 15:40:54

{ "message":"API rate limit exceeded" }

**Comment by rafabayona** [comment]
I'm also having this error in my logs. How did you update your webserver? @domotiquemaison07  Mine is in v3.16

**Comment by domotiquemaison07** [comment]
@rafabayona
In the main menu of your Airzonecloud web interface
Select the Airtools section and click on your installation.
On the right of your firmware version the icon shows you if an update is available.
